#!/bin/bash

source $(dirname $0)/build-common
Load_ISO openstack

cd $(dirname $0)/../openstack

PACKER_LOG=1 packer build ${FILE:-openstack-qemu.json}

RANCHEROS_VERSION=${RANCHEROS_VERSION:-test}

mv output-openstack/packer-openstack rancheros-openstack.qcow2
qemu-img convert -c -O qcow2 rancheros-openstack.qcow2 rancheros-openstack.img
mkdir -p ../dist
mv rancheros-openstack.img ../dist/

echo "upload the openstack image using:"
echo "  gsutil cp dist/rancheros-openstack.img gs://releases.rancher.com/os/latest/rancheros-openstack.img"
echo "  gsutil cp dist/rancheros-openstack.img gs://releases.rancher.com/os/${RANCHEROS_VERSION}/rancheros-openstack.img"
echo "upload the github release:"
echo "  github-release upload  --user rancher --repo os --tag ${RANCHEROS_VERSION} --file dist/rancheros-openstack.img --name rancheros-openstack.img"
