#!/bin/bash

# Build the RancherOS bootstrap image used by the real AMI builders
# this bootstrap's a RancherOS from an ubuntu AMI
# not really needed often - because we can re-use the existing buildre-image

cd $(dirname $0)/../amazon

if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
    echo AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be set
fi

export BOOTSTRAP_CONTAINER=rancher/os:v0.7.1

packer build ${FILE:-rancheros-aws-ami-builder.json}
