#!/bin/bash

source $(dirname $0)/build-common
Load_ISO azure

cd $(dirname $0)/../azure

PACKER_LOG=1 packer build ${FILE:-azure-qemu.json}
# ======================================================================================================================
# resize VHD size, azure need to align to 1MB
# ======================================================================================================================
RAW="rancheros-azure.raw"

VHD="rancheros-azure.vhd"

MB=$((1024*1024))

RANCHEROS_VERSION=${RANCHEROS_VERSION:-test}

mv output-azure/packer-azure $RAW

mkdir -p ../dist

mv $RAW ../dist/

size=$(qemu-img info -f raw --output json "../dist/$RAW" | \

gawk 'match($0, /"virtual-size": ([0-9]+),/, val) {print val[1]}')

ROUNDED=$((($size/$MB + 1)*$MB))

qemu-img resize ../dist/$RAW $ROUNDED

qemu-img convert -f raw -o subformat=fixed,force_size -O vpc ../dist/$RAW ../dist/$VHD

rm -rf ../dist/$RAW
# ======================================================================================================================
# upload VHD to azure
# ======================================================================================================================
echo "upload the Azure image using:"
echo "  ./scripts/azure/pre-release-azure-img.sh"
echo "upload the GCP image using:"
echo "  gsutil cp dist/rancheros-azure.vhd gs://releases.rancher.com/os/latest/rancheros-azure.vhd"
echo "  gsutil cp dist/rancheros-azure.vhd gs://releases.rancher.com/os/${RANCHEROS_VERSION}/rancheros-azure.vhd"
echo "upload the github release:"
echo "  github-release upload  --user rancher --repo os --tag ${RANCHEROS_VERSION} --file dist/rancheros-azure.vhd --name rancheros-azure.vhd"
