#!/bin/bash

source $(dirname $0)/build-common
Load_ISO exoscale

cd $(dirname $0)/../exoscale

PACKER_LOG=1 packer build ${FILE:-exoscale-qemu.json}

RANCHEROS_VERSION=${RANCHEROS_VERSION:-test}

mv output-exoscale/packer-exoscale rancheros-exoscale.qcow2
qemu-img convert -c -O qcow2 rancheros-exoscale.qcow2 rancheros-exoscale.img
mkdir -p ../dist
mv rancheros-exoscale.img ../dist/

echo "upload the Exoscale image using:"
echo "  gsutil cp dist/rancheros-exoscale.img gs://releases.rancher.com/os/latest/rancheros-exoscale.img"
echo "  gsutil cp dist/rancheros-exoscale.img gs://releases.rancher.com/os/${RANCHEROS_VERSION}/rancheros-exoscale.img"
echo "upload the github release:"
echo "  github-release upload  --user rancher --repo os --tag ${RANCHEROS_VERSION} --file dist/rancheros-exoscale.img --name rancheros-exoscale.img"
