#!/bin/bash

cd $(dirname $0)/../gce

export ISO_CHECKSUM=$(cat /iso-checksums.txt | grep md5 | sed 's/md5: \(.*\)  rancheros.iso/\1/')

PACKER_LOG=1  packer build ${FILE:-gce-qemu.json}

RANCHEROS_VERSION=${RANCHEROS_VERSION:-test}

mv output-qemu-googlecompute/packer-qemu-googlecompute disk.raw
tar czvf rancheros-${RANCHEROS_VERSION}.tar.gz disk.raw
mkdir -p ../dist
mv rancheros-${RANCHEROS_VERSION}.tar.gz ../dist/

echo "upload the GCE image using:"
echo "  gsutil cp dist/rancheros-${RANCHEROS_VERSION}.tar.gz gs://releases.rancher.com/os/latest"
echo "  gsutil cp dist/rancheros-${RANCHEROS_VERSION}.tar.gz gs://releases.rancher.com/os/${RANCHEROS_VERSION}"
echo "upload the github release:"
echo "  github-release upload  --user rancher --repo os --tag ${RANCHEROS_VERSION} --file dist/rancheros-${RANCHEROS_VERSION}.tar.gz --name rancheros-${RANCHEROS_VERSION}.tar.gz"

# and then push to gce
# gsutil cp ./rancheros-${RANCHEROS_VERSION}.tar.gz gs://ros-images/
## gcloud compute images create rancheros-v0.7.0 —source-uri gs://ros-images/rancheos-v0.7.0
## https://cloud.google.com/sdk/docs/quickstart-linux
