#!/bin/bash

source $(dirname $0)/build-common
Load_ISO pingan

cd $(dirname $0)/../pingan

PACKER_LOG=1 packer build ${FILE:-pingan-qemu.json}

RANCHEROS_VERSION=${RANCHEROS_VERSION:-test}

mkdir -p ../dist
mv output-pingan-ecs/packer-pingan-ecs ../dist/rancheros-pingan.qcow2

echo "upload the pingan image using:"
echo "  gsutil cp dist/rancheros-pingan.qcow2 gs://releases.rancher.com/os/latest/rancheros-pingan.qcow2"
echo "  gsutil cp dist/rancheros-pingan.qcow2 gs://releases.rancher.com/os/${RANCHEROS_VERSION}/rancheros-pingan.qcow2"
echo "upload the github release:"
echo "  github-release upload  --user rancher --repo os --tag ${RANCHEROS_VERSION} --file dist/rancheros-pingan.qcow2 --name rancheros-pingan.qcow2"
