#!/bin/bash

cd $(dirname $0)/../digitalocean

PACKER_LOG=1 packer build ${FILE:-digitalocean-qemu.json}

RANCHEROS_VERSION=${RANCHEROS_VERSION:-test}

mv output-digitalocean/packer-digitalocean rancheros-digitalocean.qcow2
qemu-img convert -c -O qcow2 rancheros-digitalocean.qcow2 rancheros-digitalocean.img
mkdir -p ../dist
mv rancheros-digitalocean.img ../dist/

echo "upload the digitalocean image using:"
echo "  gsutil cp dist/rancheros-digitalocean.img gs://releases.rancher.com/os/latest/rancheros-digitalocean.img"
echo "  gsutil cp dist/rancheros-digitalocean.img gs://releases.rancher.com/os/${RANCHEROS_VERSION}/rancheros-digitalocean.img"
echo "upload the github release:"
echo "  github-release upload  --user rancher --repo os --tag ${RANCHEROS_VERSION} --file dist/rancheros-digitalocean.img --name rancheros-digitalocean.img"
