#!/bin/bash


cat > /boot/grub/menu.lst <<EOF
default 0
timeout 0
fallback 1

hiddenmenu

title RancherOS 0.0.6
root (hd0)
kernel /boot/vmlinuz-0.0.6-rancheros rancher.cloud_init.datasources=[ec2]
initrd /boot/initrd-0.0.6-rancheros

title           Ubuntu 14.04.1 LTS, kernel 3.13.0-44-generic
root            (hd0)
kernel          /boot/vmlinuz-3.13.0-44-generic root=LABEL=cloudimg-rootfs ro console=hvc0
initrd          /boot/initrd.img-3.13.0-44-generic

EOF
